### ISSUE TITLE
Lena demo doesn't work well

### ISSUE THREAD

**Issue by MSKTHU** [yqueau/shape_from_shading#1]
I run the lena demo without changing any code. It said that the iteration was stopped because the algorithm didn't converge. Could you help me with this demo?

**Comment by yqueau** [comment]
Hello, 

I just executed it and it run perfectly : can you tell me more about the error you get ? 

In case it is only the inner PCG iterations which do not converge, this is expected : there is no need for them to reach full convergence for the outer loop to converge. 

Best,
Yvain

**Comment by MSKTHU** [comment]
> Hello,
> 
> I just executed it and it run perfectly : can you tell me more about the error you get ?
> 
> In case it is only the inner PCG iterations which do not converge, this is expected : there is no need for them to reach full convergence for the outer loop to converge.
> 
> Best,
> Yvain

Hi, here are the results I got. Are they the same as yours?

![Initialization](https://user-images.githubusercontent.com/26538235/83881704-a3d5d900-a773-11ea-9280-e1476907c0a5.jpg)
![result](https://user-images.githubusercontent.com/26538235/83881800-c8ca4c00-a773-11ea-8ad8-432236a6e63f.jpg)

A different view of the result
![result2](https://user-images.githubusercontent.com/26538235/83882331-86553f00-a774-11ea-873f-a12392523927.jpg)

**Comment by yqueau** [comment]
Yes, this is the expected result !

**Comment by MSKTHU** [comment]
THANKS！！
