### ISSUE TITLE
Can't identify 'simulate_image_ortho'

### ISSUE THREAD

**Issue by tilanta** [yqueau/shape_from_shading#2]
Hi, when I ran the demo3-5 code, it raised error of "can't identify 'simulate_image_ortho'", and I did't find this function too.

**Comment by yqueau** [comment]
Hi, 

Thank you for pointing out these missing functions. I just added them to the Toolbox/ folder. 

Best,
Yvain

**Comment by tilanta** [comment]
> 
> 
> Hi,
> 
> Thank you for pointing out these missing functions. I just added them to the Toolbox/ folder.
> 
> Best,
> Yvain

Thank you very much!!!
