### ISSUE TITLE
How to test my own image

### ISSUE THREAD

**Issue by tilanta** [yqueau/shape_from_shading#3]
Hi,

I wonder how to test my own image on your code? Sorry for disturbing you, I'm a rookie in SFS and I really appreciate you can release your codes.

Best wishes,

Tian

**Comment by yqueau** [comment]
Hi, 

To run the code on your own image, you just need to change the image name in the script to yours. Example on the "demo_1", l.17, just change 

data.I = imresize(rgb2gray(imread('Data/lena.png')),0.5); 

to something like

data.I = rgb2gray(imread('Path/to/your_image.png'));

Best,
Yvain

**Comment by tilanta** [comment]
> Hi,
> 
> To run the code on your own image, you just need to change the image name in the script to yours. Example on the "demo_1", l.17, just change
> 
> data.I = imresize(rgb2gray(imread('Data/lena.png')),0.5);
> 
> to something like
> 
> data.I = rgb2gray(imread('Path/to/your_image.png'));
> 
> Best,
> Yvain

Oh thank you very much, I have tested my images successfully!

Best,
Tian
